version: "3.8"
services:
  web:
    build: .
    command: python /BookStore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/BookStore
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.7
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes: 
  postgres_data:
